### ISSUE TITLE
Advanced name cleaning method: italics?!?

### ISSUE THREAD

**Issue by austinmeier** [Planteome/samara#56]
So... After investigating the diseases of rice, or diseases of maize, we have identified a few patterns that seem to cause the name matching to choke.  This results in a significant number of `no:match` results that appear to be pretty straightforward matches.  Originally I was going to lay out examples of each "pattern" so that your name cleaning could more effectively deal with these.  However, after some discussion with @marieALaporte, we determined that the most consistent formatting that APSnet.org has, is actually the FONT!!  

After looking through the disease pages, it appears that you could strip everything except the text that is in italics.  I don't know exactly how you are scraping the text, but the HTML contains the `<i>` tag, so I believe it to be possible.

Another pattern that we noticed while looking through apsnet is the indentation is what defines different diseases.  The outermost indented line is the disease name.  Then the indented lines below it are the pathogens that cause the above disease.  I don't know if that helps in any way, but it seemed like it might be useful, and because we are grasping at straws for how apsnet formats these disease pages, I figured anything would help!

We are pausing our efforts on this for now.  Hopefully extracting italics and running the name matching on those results will produce better results.

**Comment by jhpoelen** [comment]
Interesting! I poked around a bit and found that the italic tags are used in a pretty inconsistent way.

for instance from the peach and nectarines:
```
<i>
<dd>Pseudomonas syringae</i> pv. <i>syringae</i> van Hall 1902 
```
Notice how the <dd> element (used to detect names now) is breaking the scope of the italic. 

also, there's names like:
```
<dd>
 <i>‘Candidatus</i> Phytoplasma asteris’
</dd>
```

So, I am a bit hesitant to declare victory on this one. I'll poke around some more.

**Comment by austinmeier** [comment]
I knew it would be trouble to assume apsnet did anything with consistency!

A few things that would clean up the taxon matching aside from italics:

1. removing parenthetical clauses
2. removing any word that is followed by "et al"

**Comment by jhpoelen** [comment]
Thanks for the suggestions. My experience with this APS is also that inconsistencies are pretty consistent. 

Could you please provide explicit examples?

**Comment by austinmeier** [comment]
sure! 
`Leaf smut	Eballistra oryzae (Syd. & P. Syd.) R. Bauer, Begerow, A. Nagler & Oberw.	Eballistra oryzae (Syd. & P. Syd.) R. Bauer	no:match	pathogen of	http://purl.obolibrary.org/obo/RO_0002556	Diseases of Rice (Oryza and Zizania spp.)	Oryza and Zizania spp.	no:match	leaf	PO:0025034	R. D. Cartwright, D. E. Groth, Y. A. Wamishe, C. A. Greer, L. A. Calvert, C. M. Vera Cruz, V. Verdier, and M. O. Way, primary collators (last update: 9/1/17). Diseases of Rice (Oryza and Zizania spp.). The American Phytopathological Society. Accessed on 2018-03-08 at http://www.apsnet.org/publications/commonnames/Pages/Rice.aspx	http://www.apsnet.org/publications/commonnames/Pages/Rice.aspx	2018-03-08`  
fails to find a match on `Eballistra oryzae (Syd. & P. Syd.) R. Bauer`, but if you remove everything after the `(` and search for just `Eballistra oryzae`, you get a pretty easy match of NCBITaxon:127114

In addition, just using http://resolver.globalnames.org/ searching for the entire Eballistra oryzae (Syd. & P. Syd.) R. Bauer` it returns a correct NCBI taxon with a confidence score of 0.988.  I'd say that's pretty darn good!


I'm struggling to find a good example of the 'et al.' pattern that doesn't also get fixed by using the parenthesis pattern above... stay tuned.

**Comment by jhpoelen** [comment]
Yep, global names is pretty good at names parsing. I ran all the no:match names through global names and quite a few return with one or more matches to NCBI. See attached. 
[names_gn.zip](https://github.com/jhpoelen/samara/files/1795190/names_gn.zip)

The reason why GloBI didn't pick this up is because it uses globalnames as a secondary resolver. Might have to revisit that idea.

**Comment by jhpoelen** [comment]
Before we take any next steps, I'd like to suggest to add these mapping to our taxonMap.tsv . Agree?

**Comment by austinmeier** [comment]
Agreed.  Quick question:  What does the `SIMILAR_TO`, and `SAME_AS` column mean?  Is that some degree of accuracy?

**Comment by jhpoelen** [comment]
SAME_AS ~> exact canonical match 
SIMILAR_TO ~> fuzzy canonical match

**Comment by jhpoelen** [comment]
For weird duplicates like below, we might be able to cross reference against wikidata (e.g., https://www.wikidata.org/wiki/Q134359 only has single NCBI taxon link). Perhaps best to discuss. Do you have time for a chat?

no:match | Aspergillus fumigatus Fresen. | NCBI:1035095 | Aspergillus fumigatus | \| Eukaryota \| Opisthokonta \| Fungi \| Dikarya \| Ascomycota \|  \| Pezizomycotina \|  \| Eurotiomycetes \| Eurotiomycetidae \| Eurotiales \| Aspergillaceae \| Aspergillus \| Aspergillus fumigatus \| Aspergillus fumigatus | https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=1035095
-- | -- | -- | -- | -- | --
no:match | Aspergillus fumigatus Fresen. | NCBI:1127031 | Aspergillus fumigatus | \| Eukaryota \| Opisthokonta \| Fungi \| Dikarya \| Ascomycota \|  \| Pezizomycotina \|  \| Eurotiomycetes \| Eurotiomycetidae \| Eurotiales \| Aspergillaceae \| Aspergillus \| Aspergillus fumigatus \| Aspergillus fumigatus | https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=1127031
no:match | Aspergillus fumigatus Fresen. | NCBI:1127033 | Aspergillus fumigatus | \| Eukaryota \| Opisthokonta \| Fungi \| Dikarya \| Ascomycota \|  \| Pezizomycotina \|  \| Eurotiomycetes \| Eurotiomycetidae \| Eurotiales \| Aspergillaceae \| Aspergillus \| Aspergillus fumigatus \| Aspergillus fumigatus | https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=1127033
no:match | Aspergillus fumigatus Fresen. | NCBI:1266464 | Aspergillus fumigatus | \| Eukaryota \| Opisthokonta \| Fungi \| Dikarya \| Ascomycota \|  \| Pezizomycotina \|  \| Eurotiomycetes \| Eurotiomycetidae \| Eurotiales \| Aspergillaceae \| Aspergillus \| Aspergillus fumigatus \| Aspergillus fumigatus | https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=1266464
no:match | Aspergillus fumigatus Fresen. | NCBI:1437362 | Aspergillus fumigatus | \| Eukaryota \| Opisthokonta \| Fungi \| Dikarya \| Ascomycota \|  \| Pezizomycotina \|  \| Eurotiomycetes \| Eurotiomycetidae \| Eurotiales \| Aspergillaceae \| Aspergillus \| Aspergillus fumigatus \| Aspergillus fumigatus | https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=1437362
no:match | Aspergillus fumigatus Fresen. | NCBI:1456794 | Aspergillus fumigatus | \| Eukaryota \| Opisthokonta \| Fungi \| Dikarya \| Ascomycota \|  \| Pezizomycotina \|  \| Eurotiomycetes \| Eurotiomycetidae \| Eurotiales \| Aspergillaceae \| Aspergillus \| Aspergillus fumigatus \| Aspergillus fumigatus | https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=1456794
no:match | Aspergillus fumigatus Fresen. | NCBI:1456795 | Aspergillus fumigatus | \| Eukaryota \| Opisthokonta \| Fungi \| Dikarya \| Ascomycota \|  \| Pezizomycotina \|  \| Eurotiomycetes \| Eurotiomycetidae \| Eurotiales \| Aspergillaceae \| Aspergillus \| Aspergillus fumigatus \| Aspergillus fumigatus | https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=1456795
no:match | Aspergillus fumigatus Fresen. | NCBI:1476192 | Aspergillus fumigatus | \| Eukaryota \| Opisthokonta \| Fungi \| Dikarya \| Ascomycota \|  \| Pezizomycotina \|  \| Eurotiomycetes \| Eurotiomycetidae \| Eurotiales \| Aspergillaceae \| Aspergillus \| Aspergillus fumigatus \| Aspergillus fumigatus | https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=1476192
no:match | Aspergillus fumigatus Fresen. | NCBI:330879 | Aspergillus fumigatus | \| Eukaryota \| Opisthokonta \| Fungi \| Dikarya \| Ascomycota \|  \| Pezizomycotina \|  \| Eurotiomycetes \| Eurotiomycetidae \| Eurotiales \| Aspergillaceae \| Aspergillus \| Aspergillus fumigatus \| Aspergillus fumigatus | https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=330879
no:match | Aspergillus fumigatus Fresen. | NCBI:451804 | Aspergillus fumigatus | \| Eukaryota \| Opisthokonta \| Fungi \| Dikarya \| Ascomycota \|  \| Pezizomycotina \|  \| Eurotiomycetes \| Eurotiomycetidae \| Eurotiales \| Aspergillaceae \| Aspergillus \| Aspergillus fumigatus \| Aspergillus fumigatus | https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=451804
no:match | Aspergillus fumigatus Fresen. | NCBI:505235 | Aspergillus fumigatus | \| Eukaryota \| Opisthokonta \| Fungi \| Dikarya \| Ascomycota \|  \| Pezizomycotina \|  \| Eurotiomycetes \| Eurotiomycetidae \| Eurotiales \| Aspergillaceae \| Aspergillus \| Aspergillus fumigatus \| Aspergillus fumigatus | https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=505235
no:match | Aspergillus fumigatus Fresen. | NCBI:746128 | Aspergillus fumigatus | \| Eukaryota \| Opisthokonta \| Fungi \| Dikarya \| Ascomycota \|  \| Pezizomycotina \|  \| Eurotiomycetes \| Eurotiomycetidae \| Eurotiales \| Aspergillaceae \| Aspergillus \| Aspergillus fumigatus | https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=746128
no:match | Aspergillus fumigatus Fresen. | NCBI:888744 | Aspergillus fumigatus | \| Eukaryota \| Opisthokonta \| Fungi \| Dikarya \| Ascomycota \|  \| Pezizomycotina \|  \| Eurotiomycetes \| Eurotiomycetidae \| Eurotiales \| Aspergillaceae \| Aspergillus \| Aspergillus fumigatus \| Aspergillus fumigatus | https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=888744

**Comment by austinmeier** [comment]
Yeah sure; appear.in?

**Comment by jhpoelen** [comment]
Just added the de-duplicated exact matches from globalnames see https://github.com/jhpoelen/samara/commit/2d48bfbcbb1dd9645e40f4b9af12d6a6d40ac210 .

**Comment by jhpoelen** [comment]
Change resulting in extra ~ 1k names being matched.

```
$ cat apsnet.tsv | grep "no:match" | wc -l
7651
$ cat apsnet_post_gn.tsv | grep "no:match" | wc -l
6405

**Comment by jhpoelen** [comment]
@austinmeier @marieALaporte please note that after doing a global names match on latest aps scrape via elton/nomer (see attached result 
[names_post_gn_second_gn.tsv.zip](https://github.com/jhpoelen/samara/files/1797829/names_post_gn_second_gn.tsv.zip)
), 1714 names still need some attention.

1. there's no more exact NCBI matches coming via globalnames (as expected):
```
$ cat names_post_gn_second_gn.tsv | grep SAME_AS | grep NCBI | awk -F '\t' '{ print $2 }' | sort | uniq | wc -l
0
```
2. there 752 exact non-NCBI matches coming via globalnames:
```
$ cat names_post_gn_second_gn.tsv | grep SAME_AS | grep -v NCBI | awk -F '\t' '{ print $2 }' | sort | uniq | wc -l
752
```
3. 88 names have fuzzy matches to NCBI term via globalnames:
```
$ less names_post_gn_second_gn.tsv | grep SIMILAR_TO | grep NCBI | awk -F '\t' '{ print $2 }' | sort | uniq | wc -l
88
```
4. 175 names have fuzzy matches to non-NCBI term via globalnames:
```
$ less names_post_gn_second_gn.tsv | grep SIMILAR_TO | grep -v NCBI | awk -F '\t' '{ print $2 }' | sort | uniq | wc -l
175
```
5. 691 names have exact synonym matches, but none from NCBI.  
```
$ cat names_post_gn_second_gn.tsv | grep SYNONYM | awk -F '\t' '{ print $2 }' | sort | uniq | wc -l
691
```
6. 473 names have no matches whatsoever
```
$ cat names_post_gn_second_gn.tsv | grep NONE | awk -F '\t' '{ print $2 }' | sort | uniq | wc -l
473
```

This adds up to 2179 names which can be explained by duplicate matches by globalnames or matches that match differently to different taxonomies.

**Comment by jhpoelen** [comment]
Some poking around, seems that species -> genus mapping and resolving of synonyms via OTT (open tree of life) would increase our name match percentage. In the former, taxonomies other than NCBI know  about a species, but NCBI only knows the genus. The latter, OTT seems a little better at resolving synonyms via globalnames that NCBI does. Mapping to the synonymized name via OTT/gn shows some potential. (e.g., ```Aecidium meliosmae-myrianthae P. Hennings & Shirai      SYNONYM_OF      OTT:943268      Phakopsora euvitis``` would map to https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=460369 ). And . . . looking at the source text ```Phakopsora euvitis Y. Ono (syn. Aecidium meliosmae-myrianthae P. Hennings & Shirai)``` from http://www.apsnet.org/publications/commonnames/Pages/Grape.aspx this issue is not quite important, because the main taxon has already been resolved (see e.g., https://www.globalbioticinteractions.org/?interactionType=interactsWith&sourceTaxon=NCBI%3A460369 ).

**Comment by austinmeier** [comment]
I think so long as we can preserve the original text, and perhaps the OTT match somehow, we could add those things in as synonyms/comments in the ontology term after creation.

**Comment by jhpoelen** [comment]
Closing stale issue.
