### ISSUE TITLE
apsnet common disease pages no longer available via http://www.apsnet.org/publications/commonnames/Pages/default.aspx

### ISSUE THREAD

**Issue by jhpoelen** [Planteome/samara#57]
Samara supports extracting of plant diseases from http://www.apsnet.org/publications/commonnames/Pages/default.aspx . 

After checking logs, it appears that the resources are no longer available via apsnet.org. Thanks to https://build.berkeleybop.org/view/Planteome/job/extract-apsnet-diseases , I was able to see that the pages were last seen on 11 Oct 2018 . The last available scrape has been included in the repository at https://github.com/globalbioticinteractions/aps . 

from https://build.berkeleybop.org/view/Planteome/job/extract-apsnet-diseases/168/console :
```
[http://www.apsnet.org/publications/commonnames/Pages/default.aspx] download failed because of:
org.jsoup.HttpStatusException: HTTP error fetching URL. Status=404, URL=https://www.apsnet.org/publications/commonnames/Pages/default.aspx
```

**Comment by jhpoelen** [comment]
@cmungall @marieALaporte @jaiswalp - please note that APS's common names for disease pages were last available on 2018-10-11 . I was unable to find the new location of the pages if there is any. Please holler if you know more about this.

**Comment by marieALaporte** [comment]
This is the new [link](https://www.apsnet.org/edcenter/resources/commonnames/Pages/default.aspx). They just changed the website apparently. 
@jhpoelen, are you trying to update the data?

**Comment by jhpoelen** [comment]
Turns out that the pages were moved to https://www.apsnet.org/edcenter/resources/commonnames/Pages/default.aspx . . . updating .

**Comment by jhpoelen** [comment]
Thanks @marieALaporte  .

**Comment by jhpoelen** [comment]
@marieALaporte the job at https://build.berkeleybop.org/view/Planteome/job/extract-apsnet-diseases has been updating the data on a regular interval. Until today, GloBI was harvesting the most recent aps scrape.

**Comment by jhpoelen** [comment]
Updated samara to use new endpoint. Please note that workarounds for new issues #58 and #59 were implemented. Ideally, we'd convince the American Phytopathological Society to publish their common names for diseases in a more structured format.
